#return statement = fuctions send Python values/objects back to the caller
#                   these values\objects are known as fuction's return ValueError

def multiply(number1,number2):
  result = number1 * number2
  return result #or return number1 * number2

x = multiply(6,8)
print(multiply(6,8))
